FROM eclipse-mosquitto:2.0
COPY mosquitto.conf /mosquitto/config/mosquitto.conf
COPY certs /mosquitto/certs
# mosquito imagen ya hace por defecto 
#ENTRYPOINT ["/usr/sbin/mosquitto"]
#CMD ["-c", "/mosquitto/config/mosquitto.conf"]
# asi se conecta. 